th -i main.lua \
    -load_seed false \
    -path2seed ./sk1/seed.save \
    -optimizer ADAGRAD \
    -learning_rate 1e-1 \
    -criterion NLL \
    -plot_every 2000 \
    -batch_size 200 \
    -epoch 1000 \
    -save_every 1 \
    -load_model false \
    -path2model ./sk1/cade.net \
    -model_type overfeat \
    -dropout 0.50 \
    -data_type Recipe101 \
    -path2dir /home/cadene/data/recipe_101_clean/ \
    -run true \
    -train true \
    -test true \
    -type cuda \
    -cudnn false \
    -threads 1 \
    -gpuid 1 \
    -path2save ./sk1/ 
