th -i main.lua \
    -optimizer ADAGRAD \
    -learning_rate 1e-2 \
    -criterion NLL \
    -plot_every 2000 \
    -batch_size 200 \
    -epoch 1000 \
    -save_every 10 \
    -load_model false \
    -path2model ./save_mbp_2/cade.net \
    -model_type verydeep_A \
    -dropout 0.50 \
    -data_type Recipe101 \
    -path2dir /Users/remicadene/data/recipe_101_tiny/ \
    -run true \
    -train true \
    -test false \
    -type float \
    -cudnn false \
    -threads 1 \
    -gpuid 1 \
    -path2save ./save_mbp_2/ 
