th -i main.lua \
    -optimizer ADAGRAD \
    -learning_rate 1e-2 \
    -criterion NLL \
    -plot_every 2000 \
    -batch_size 200 \
    -epoch 1000 \
    -save_every 1 \
    -load_model false \
    -path2model ./save_kepler_2/cade.net \
    -model_type overfeat_scratch \
    -dropout 0.30 \
    -data_type Recipe101 \
    -path2dir /home/cadene/data/recipe_101_clean/ \
    -run true \
    -train true \
    -test false \
    -type cuda \
    -cudnn false \
    -threads 1 \
    -gpuid 2 \
    -path2save ./save_kepler_2/ 
